name: Auto Tag on Merge

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  tag-version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # needed to fetch all tags

      - name: Get version from file
        id: get_version
        run: echo "version=v$(cat VERSION)" >> $GITHUB_OUTPUT

      - name: Check if tag exists
        id: check_tag
        run: |
          TAG="v$(cat VERSION)"
          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create and push tag
        if: steps.check_tag.outputs.exists == 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag "v$(cat VERSION)"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} "v$(cat VERSION)"